In [38]:
### Predict whether the applicant is eligible for loan or not(Loan_Status)
### import the packages
### load the ds
### df= df.drop("Loan_ID",axis=1)
### shape
### sample of 10 records
### info
### describe
### describe all
### hist
### boxplot for all numerical columns
### countplot for all categorical columns

### Loan_status Vs all categorical columns (countplot)
### Loan_status Vs all numerical columns (Box/Violin)

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/loan_prediction.csv")

In [40]:
df= df.drop("Loan_ID",axis=1)

In [41]:
df.shape

(614, 12)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             601 non-null    object
 1   Married            611 non-null    object
 2   Dependents         599 non-null    object
 3   Education          614 non-null    object
 4   Self_Employed      582 non-null    object
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object
 11  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [43]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [44]:
614-592

22

In [45]:
### Lot of outliers and skewness

In [46]:
### Business Understanding -> Model to predict whether the customer is eligible for loan or not
### Analytic approach -> ML -> SL -> Classification -> Binary classification
### Data Req and Data collection
### Data Understanding
### Data Preparation
### Modelling and evaluation
### Deployment and feedback

In [47]:
### Data Preparation -> Drop insignificant column/columns -> Treating the missing values -> Categ into num columns

In [48]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [49]:
### Numerical -> Mean/Median
### Categorical -> Mode

In [50]:
median_loanamount=df["LoanAmount"].median()
median_loanamount

128.0

In [51]:
df["LoanAmount"]=df["LoanAmount"].replace(np.nan,median_loanamount)

In [52]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [53]:
### replace for loan amount term and credit history

In [54]:
median_term=df["Loan_Amount_Term"].median()

In [55]:
df["Loan_Amount_Term"]=df["Loan_Amount_Term"].replace(np.nan,median_term)

In [56]:
median_credit=df["Credit_History"].median()

In [57]:
df["Credit_History"]=df["Credit_History"].replace(np.nan,median_credit)

In [58]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [59]:
mode_gender=df["Gender"].mode()[0]
mode_gender

'Male'

In [60]:
df["Gender"]=df["Gender"].replace(np.nan,mode_gender)

In [61]:
mode_married=df["Married"].mode()[0]

In [62]:
mode_employed=df["Self_Employed"].mode()[0]

In [63]:
mode_dep=df["Dependents"].mode()[0]

In [64]:
df["Married"]=df["Married"].replace(np.nan,mode_married)

In [65]:
df["Dependents"]=df["Dependents"].replace(np.nan,mode_dep)

In [66]:
df["Self_Employed"]=df["Self_Employed"].replace(np.nan,mode_employed)

In [67]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [68]:
df.sample(10)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
565,Male,Yes,0,Not Graduate,No,4467,0.0,120.0,360.0,1.0,Rural,Y
187,Male,Yes,0,Graduate,No,2383,2138.0,58.0,360.0,1.0,Rural,Y
572,Male,Yes,2,Graduate,No,16666,0.0,275.0,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
293,Female,No,0,Graduate,No,5417,0.0,143.0,480.0,0.0,Urban,N
459,Male,Yes,0,Graduate,No,8334,0.0,160.0,360.0,1.0,Semiurban,N
162,Male,Yes,1,Graduate,No,3089,1280.0,121.0,360.0,0.0,Semiurban,N
432,Male,No,0,Graduate,No,12876,0.0,405.0,360.0,1.0,Semiurban,Y
343,Male,Yes,3+,Not Graduate,No,3173,0.0,74.0,360.0,1.0,Semiurban,Y
137,Male,Yes,2,Graduate,Yes,3316,3500.0,88.0,360.0,1.0,Urban,Y

In [69]:
df = pd.get_dummies(df, drop_first=True)
df

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Male,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_Y
0,5849,0.0,128.0,360.0,1.0,True,False,False,False,False,False,False,False,True,True
1,4583,1508.0,128.0,360.0,1.0,True,True,True,False,False,False,False,False,False,False
2,3000,0.0,66.0,360.0,1.0,True,True,False,False,False,False,True,False,True,True
3,2583,2358.0,120.0,360.0,1.0,True,True,False,False,False,True,False,False,True,True
4,6000,0.0,141.0,360.0,1.0,True,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,2900,0.0,71.0,360.0,1.0,False,False,False,False,False,False,False,False,False,True
610,4106,0.0,40.0,180.0,1.0,True,True,False,False,True,False,False,False,False,True
611,8072,240.0,253.0,360.0,1.0,True,True,True,False,False,False,False,False,True,True
612,7583,0.0,187.0,360.0,1.0,True,True,False,True,False,False,False,False,True,True
613,4583,0.0,133.0,360.0,0.0,False,False,False,False,False,False,True,True,False,False

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ApplicantIncome          614 non-null    int64
 1   CoapplicantIncome        614 non-null    float64
 2   LoanAmount               614 non-null    float64
 3   Loan_Amount_Term         614 non-null    float64
 4   Credit_History           614 non-null    float64
 5   Gender_Male              614 non-null    bool
 6   Married_Yes              614 non-null    bool
 7   Dependents_1             614 non-null    bool
 8   Dependents_2             614 non-null    bool
 9   Dependents_3+            614 non-null    bool
 10  Education_Not Graduate   614 non-null    bool
 11  Self_Employed_Yes        614 non-null    bool
 12  Property_Area_Semiurban  614 non-null    bool
 13  Property_Area_Urban      614 non-null    bool
 14  Loan_Status_Y            614 non-null    bool
dtypes: bool(10), float64(4), int64(1)
memory usage: 30.1 KB

In [71]:
Y=df["Loan_Status_Y"]
X=df.drop("Loan_Status_Y",axis=1)

In [72]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [73]:
from sklearn.linear_model import LogisticRegression
model_lr=LogisticRegression()
model_lr.fit(X_train,Y_train)
print(model_lr.score(X_train,Y_train))
print(model_lr.score(X_test,Y_test))

0.8135198135198135
0.8054054054054054

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [74]:
from sklearn.neighbors import KNeighborsClassifier
model_kn=KNeighborsClassifier()
model_kn.fit(X_train,Y_train)
print(model_kn.score(X_train,Y_train))
print(model_kn.score(X_test,Y_test))

0.7319347319347319
0.6270270270270271

In [76]:
from sklearn.svm import SVC
model_svc=SVC()
model_svc.fit(X_train,Y_train)
print(model_svc.score(X_train,Y_train))
print(model_svc.score(X_test,Y_test))

0.6946386946386947
0.6864864864864865

In [77]:
from sklearn.tree import DecisionTreeClassifier
model_dt=DecisionTreeClassifier()
model_dt.fit(X_train,Y_train)
print(model_dt.score(X_train,Y_train))
print(model_dt.score(X_test,Y_test))

1.0
0.7189189189189189

In [79]:
from sklearn.ensemble import BaggingClassifier
model_bg=BaggingClassifier()
model_bg.fit(X_train,Y_train)
print(model_bg.score(X_train,Y_train))
print(model_bg.score(X_test,Y_test))

0.9906759906759907
0.7621621621621621

In [80]:
from sklearn.ensemble import AdaBoostClassifier
model_ab=AdaBoostClassifier()
model_ab.fit(X_train,Y_train)
print(model_ab.score(X_train,Y_train))
print(model_ab.score(X_test,Y_test))

0.8158508158508159
0.8108108108108109

In [81]:
from sklearn.ensemble import GradientBoostingClassifier
model_gb=GradientBoostingClassifier()
model_gb.fit(X_train,Y_train)
print(model_gb.score(X_train,Y_train))
print(model_gb.score(X_test,Y_test))

0.8951048951048951
0.8054054054054054

In [82]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier()
model_rf.fit(X_train,Y_train)
print(model_rf.score(X_train,Y_train))
print(model_rf.score(X_test,Y_test))

1.0
0.7891891891891892

In [75]:
## Logistic Regression
## KNN classifier
### SVC
### DTC
### Bagging Classifier
#### ABC
### GBC
### RFC